name: Load Remote tflint Config
description: Loads a remote tflint config to a local action workspace
inputs:
  source_repo:
    description: The remote repository containing the tflint config
    required: true
  source_path:
    description: The config filepath within the source repo
    default: .tflint.hcl
  source_repo_branch:
    description: Branch of the remote repository to target
    default: main
  clone_directory_root:
    description: Root directory to clone the source repository into
    default: /tmp
  destination_path:
    description: The location in the local workspace to store the tflint config
    default: /tmp/.tflint.hcl
  token:
    description: Github access token, required for private repositories
outputs:
  path:
    description: Filepath of the retrieved tflint config
    value: ${{ inputs.destination-path }}
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_repo }}
    - ${{ inputs.source_path }}
    - ${{ inputs.source_repo_branch }}
    - ${{ inputs.clone_directory_root }}
    - ${{ inputs.destination_path }}
    - ${{ inputs.token }}
