name: Load Remote tflint Config
description: Loads a remote tflint config to a local action workspace
inputs:
  source_repo:
    description: The remote repository containing the tflint config
    required: true
  source_path:
    description: The config filepath within the source repo
    default: .tflint.hcl
  source_repo_branch:
    description: Branch of the remote repository to target
    default: main
  clone_directory_root:
    description: Root directory to clone the source repository into
    default: /tmp
  destination_filename:
    description: Name of the configuration file to be written
    default: .tflint.hcl
  token:
    description: Github access token, required for private repositories
outputs:
  filename:
    description: Filename of the copied tflint configuration
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_repo }}
    - ${{ inputs.source_path }}
    - ${{ inputs.source_repo_branch }}
    - ${{ inputs.clone_directory_root }}
    - ${{ inputs.destination_path }}
    - ${{ inputs.destination_filename }}
    - ${{ inputs.token }}
