name: Load Remote tflint Config
description: Loads a remote tflint config to a local action workspace
inputs:
  source_repo:
    description: The remote repository containing the tflint config
    required: true
  source_path:
    description: The config filepath within the source repo
    default: .tflint.hcl
  source_repo_branch:
    description: Branch of the remote repository to target
    default: main
  clone_directory_root:
    description: Root directory to clone the source repository into
    default: /tmp
  destination_directory:
    description: The directory to copy the config to within the docker container
    default: ${{ runner.temp }}
  destination_filename:
    description: Name of the config file to be written
    default: .tflint.hcl
  token:
    description: Github access token, required for private repositories
outputs:
  path:
    description: Filepath of the retrieved tflint config
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_repo }}
    - ${{ inputs.source_path }}
    - ${{ inputs.source_repo_branch }}
    - ${{ inputs.clone_directory_root }}
    - ${{ inputs.destination_path }}
    - ${{ inputs.destination_filename }}
    - ${{ inputs.token }}
